### ISSUE TITLE
Auth Token

### ISSUE THREAD

**Issue by MrPyke** [doamatto/hydro#7]
Mind if you help me obtain my Auth token?
im confused on how to get one.

My main email: \[redacted for privacy\]

thank you any way.

**Comment by doamatto** [comment]
Hey @MrPyke!

Hydro isn't complete yet, so you may experience a lot of issues when trying to use it. Regardless, you can fetch your Twitch authentication tokens at [https://dev.twitch.tv/console/apps/create](https://dev.twitch.tv/console/apps/create). Feel free to make an issue if you stumble upon something else or need some more help setting up.

Stay safe and have a good one!

Cheers
- Matt
